name = "nf-keras-hdf5"
version = "0.1.0"
license = "MIT"
author = "Milan Curcic"
maintainer = "mcurcic@miami.edu"
copyright = "Copyright 2022-2024, Milan Curcic"

[build]
external-modules = "hdf5"
link = ["hdf5", "hdf5_fortran"]

[dependencies]
functional = { git = "https://github.com/wavebitscientific/functional-fortran" }
h5fortran = { git = "https://github.com/geospace-code/h5fortran" }
json-fortran = { git = "https://github.com/jacobwilliams/json-fortran" }
neural-fortran = { git = "https://github.com/modern-fortran/neural-fortran" }
